# Generated by Django 3.1 on 2020-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_dest', models.TextField()),
                ('stree_name_address', models.TextField()),
                ('location_name_address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('designated_date', models.TextField()),
                ('intro', models.TextField()),
                ('loc', models.TextField()),
            ],
        ),
    ]
